import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { ConfigProvider, ThemeConfig } from "antd";
import LayoutMenu from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme: ThemeConfig = {
  token: {
    bg: "#f2edf3",
    firstColor: "#b66dff",
  } as any,
  components: {
    Menu: {
      itemSelectedBg: "rgb(255, 255, 255)", // خلفية العنصر المختار (شفافة شوي)
      itemSelectedColor: "#b66dff", // لون النص للعنصر المختار
      itemHoverColor: "#b66dff", // لون النص عند hover
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider theme={theme}>
          <LayoutMenu children={children} />
        </ConfigProvider>
      </body>
    </html>
  );
}
