import type { Metadata } from "next";
import "@/app/globals.css";
import { ConfigProvider, ThemeConfig } from "antd";
import LayoutMenu from "@/components/Menu";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const theme: ThemeConfig = {
  token: {
    colorBgBase: "#f2edf3",
    colorPrimary: "#b66dff",
  },
  components: {
    Menu: {
      itemSelectedBg: "rgb(255, 255, 255)", // خلفية العنصر المختار (شفافة شوي)
      itemSelectedColor: "#b66dff", // لون النص للعنصر المختار
      itemHoverColor: "#b66dff", // لون النص عند hover
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={theme}>
      <LayoutMenu>{children}</LayoutMenu>
    </ConfigProvider>
  );
}
